import Head from "next/head";
import React from "react";
import Navbar from "../nav/Navbar";

type Props = {
  children: JSX.Element;
};

function Layout({ children }: Props) {
  return (
    <div className="mx-auto font-[roboto] antialiased">
      <Head>
        <title>Bhavna international</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/main-logo.png" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <div>
          <div className="sticky top-0 z-50">
            <Navbar />
          </div>
          <main>{children}</main>
          {/* <Footer /> */}
        </div>
      </div>
    </div>
  );
}

export default Layout;
